### ISSUE TITLE
連結的顯示結果可以修改😀

### ISSUE THREAD

**Issue by garyopen1876** [monosparta/Refrigerator_Label#10]
意外發現的，顯示結果忘記修正
![IMG_5116](https://user-images.githubusercontent.com/32414355/171901435-1eeefb50-888c-4765-ae4d-7897294d4873.jpg)

修改方法
https://stackoverflow.com/questions/63927882/how-can-i-change-created-using-create-react-app-in-search-results
👍👍👍

**Comment by corbin419** [comment]
改ㄌ

**Comment by garyopen1876** [comment]
讚讚
