### ISSUE TITLE
實際無法選擇一頁呈現內容數量

### ISSUE THREAD

**Issue by leonnn124** [monosparta/Refrigerator_Label#12]
### Figma

![image](https://user-images.githubusercontent.com/50895365/171986429-f042bead-954a-4db9-b1e1-99bf8b01b1a3.png)

### Stage

![image](https://user-images.githubusercontent.com/50895365/171986434-632975cf-1968-4c4c-8de8-8a32fb66e537.png)

**Comment by garyopen1876** [comment]
已修改
