### ISSUE TITLE
寄送到期提醒信件  UI

### ISSUE THREAD

**Issue by Joe-lin-ezra** [monosparta/Refrigerator_Label#6]
建議把輸入框的拉取功能鎖起來

![image](https://user-images.githubusercontent.com/56072266/171771421-8f2ac3c9-c158-42d4-9be8-a7d044548a17.png)

**Comment by corbin419** [comment]
改好ㄌ
![image](https://user-images.githubusercontent.com/64468288/172537411-2c624f02-f269-4173-b310-cb86bc0d824b.png)
